# Generated by Django 2.1.2 on 2018-10-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
