# Generated by Django 2.1.2 on 2018-10-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagem', '0002_hospital_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='leito',
            name='categoria',
            field=models.SmallIntegerField(default=0),
        ),
    ]
